import { Industry, Ticker } from "./definitions";

//расшифровка тикеров(без платной подписки не понятно как получить)
export const TICKERS: Ticker = {
  ABIO: { name: "iАРТГЕН ао", industry: Industry.Consumer },
  ABRD: { name: "АбрауДюрсо", industry: Industry.IndustrialsFarm },
  AFKS: { name: "Система ао", industry: Industry.Financial },
  AFLT: { name: "Аэрофлот", industry: Industry.Transport },
  AGRO: { name: "AGRO-гдр", industry: Industry.IndustrialsFarm },
  AKRN: { name: "Акрон", industry: Industry.BasicMaterialsChemicals },
  ALRS: { name: "Алроса", industry: Industry.BasicMaterialsMining },
  AMEZ: { name: "АшинскийМЗ", industry: Industry.BasicMaterialsBlack },
  APTK: { name: "Аптеки 36и6", industry: Industry.Retail },
  AQUA: { name: "Инарктика", industry: Industry.IndustrialsFarm },
  ARSA: { name: "Арсагера", industry: Industry.Financial },
  ASSB: { name: "АстрЭнСб", industry: Industry.EnergySales },
  ASTR: { name: "Астра ао", industry: Industry.HighTech },
  AVAN: { name: "Авангрд ао", industry: Industry.Banks },
  BANE: { name: "Башнефт ао", industry: Industry.OilGas },
  BANEP: { name: "Башнефт ап", industry: Industry.OilGas },
  BELU: { name: "НоваБев ао", industry: Industry.Retail },
  BISVP: { name: "БашИнСв ап", industry: Industry["Telecom Services"] },
  BLNG: { name: "Белон ао", industry: Industry.BasicMaterialsMining },
  BRZL: { name: "БурЗолото", industry: Industry.BasicMaterialsGold },
  BSPB: { name: "БСП ао", industry: Industry.Banks },
  BSPBP: { name: "БСП ап", industry: Industry.Banks },
  CARM: { name: "СТГ", industry: Industry.Banks },
  CBOM: { name: "МКБ ао", industry: Industry.Banks },
  CHGZ: { name: "РН-ЗапСиб", industry: Industry.OilGas },
  CHKZ: { name: "ЧКПЗ ао", industry: Industry.BasicMaterialsBlack },
  CHMF: { name: "СевСт ао", industry: Industry.BasicMaterialsBlack },
  CHMK: { name: "ЧМК ао", industry: Industry.BasicMaterialsBlack },
  CIAN: { name: "CIAN адр", industry: Industry.Internet },
  CNTL: { name: "Телеграф ао", industry: Industry.Third },
  CNTLP: { name: "Телеграф ап", industry: Industry.Third },
  DELI: { name: "Делимобиль", industry: Industry.HighTech },
  DIAS: { name: "iДиасофт", industry: Industry.HighTech },
  DIOD: { name: "ЗаводДИОД", industry: Industry.Consumer },
  DVEC: { name: "ДЭК ао", industry: Industry.EnergySales },
  DZRD: { name: "ДонскЗавРадДеталей ао", industry: Industry.IndustrialsOther },
  DZRDP: { name: "ДонскЗавРадДеталей ап", industry: Industry.IndustrialsOther },
  EELT: { name: "ЕвроЭлТех", industry: Industry.IndustrialsOther },
  ELFV: { name: "Эл5Энер ао", industry: Industry.Energy },
  ENPG: { name: "Эн+ГРУП ао", industry: Industry.Energy },
  ETLN: { name: "ETLN-гдр", industry: Industry.Development },
  EUTR: { name: "ЕвроТранс", industry: Industry.Consumer },
  FEES: { name: "Россети", industry: Industry.Electricity },
  FESH: { name: "ДВМП ао", industry: Industry.Transport },
  FIXP: { name: "FIXP-гдр", industry: Industry.Retail },
  FLOT: { name: "Совкомфлот", industry: Industry.Transport },
  GAZA: { name: "Газ ао", industry: Industry.IndustrialsMachinery },
  GAZAP: { name: "Газ ап", industry: Industry.IndustrialsMachinery },
  GAZP: { name: "Газпром ао", industry: Industry.OilGas },
  GCHE: { name: "ЧеркизГ ао", industry: Industry.IndustrialsFarm },
  GECO: { name: "iГенетико", industry: Industry.Consumer },
  GEMA: { name: "iММЦБ ао", industry: Industry.HighTech },
  GEMC: { name: "МКПАО ЮМГ", industry: Industry.Consumer },
  GLTR: { name: "GLTR-гдр", industry: Industry.Transport },
  GMKN: { name: "ГМКНорНик", industry: Industry.BasicMaterialsColor },
  GTRK: { name: "ГТМ ао", industry: Industry.Transport },
  HHRU: { name: "iHHRU-адр", industry: Industry.Internet },
  HIMCP: {
    name: "ХимПром ап",
    industry: Industry.BasicMaterialsSpecialtyChemicals,
  },
  HNFG: { name: "ХЭНДЕРСОН", industry: Industry.Retail },
  HYDR: { name: "РусГидро ", industry: Industry.Energy },
  IGST: { name: "Ижсталь ао", industry: Industry.BasicMaterialsBlack },
  IGSTP: { name: "Ижсталь ап", industry: Industry.BasicMaterialsBlack },
  INGR: { name: "ИНГРАД ао", industry: Industry.Development },
  IRAO: { name: "ИнтерРАО ао", industry: Industry.Energy },
  IRKT: { name: "Яковлев-3", industry: Industry.IndustrialsMachinery },
  JNOS: { name: "Славн-ЯНОС ао", industry: Industry.Third },
  JNOSP: { name: "Славн-ЯНОС ап", industry: Industry.Third },
  KAZT: { name: "Куйбазот ао", industry: Industry.BasicMaterialsChemicals },
  KAZTP: { name: "Куйбазот ап", industry: Industry.BasicMaterialsChemicals },
  KBSB: { name: "ТНСэКубань", industry: Industry.EnergySales },
  KCHE: { name: "КамчатЭ ао", industry: Industry.Energy },
  KCHEP: { name: "КамчатЭ ап", industry: Industry.Energy },
  KGKC: { name: "КурганГК ао", industry: Industry.Energy },
  KGKCP: { name: "КурганГК ап", industry: Industry.Energy },
  KLSB: { name: "КалужскСК", industry: Industry.EnergySales },
  KLVZ: { name: "Кристалл", industry: Industry.Consumer },
  KMAZ: { name: "Камаз", industry: Industry.IndustrialsMachinery },
  KMEZ: { name: "КМЗ", industry: Industry.IndustrialsMachinery },
  KOGK: { name: "КоршГОК ао", industry: Industry.BasicMaterialsMining },
  KRKN: { name: "СаратНПЗ-о", industry: Industry.OilGas },
  KRKNP: { name: "СаратНПЗ-п", industry: Industry.OilGas },
  KRKOP: { name: "ТКЗКК ао", industry: Industry.IndustrialsMachinery },
  KROT: { name: "КрасОкт ао", industry: Industry.IndustrialsFarm },
  KROTP: { name: "КрасОкт ап", industry: Industry.IndustrialsFarm },
  KRSB: { name: "Красэсб ао", industry: Industry.EnergySales },
  KRSBP: { name: "Красэсб ап", industry: Industry.EnergySales },
  KUBE: { name: "РСетКубань", industry: Industry.Electricity },
  KUZB: { name: "КузнецкийБ", industry: Industry.Banks },
  KZOS: {
    name: "ОргСинт ао",
    industry: Industry.BasicMaterialsSpecialtyChemicals,
  },
  KZOSP: {
    name: "ОргСинт ап",
    industry: Industry.BasicMaterialsSpecialtyChemicals,
  },
  LEAS: { name: "Европлан", industry: Industry.Financial },
  LENT: { name: "Лента ао", industry: Industry.Retail },
  LIFE: { name: "Фармсинтез", industry: Industry.Consumer },
  LKOH: { name: "ЛУКОЙЛ", industry: Industry.OilGas },
  LNZL: { name: "Лензолото", industry: Industry.BasicMaterialsGold },
  LNZLP: { name: "Лензол ап", industry: Industry.BasicMaterialsGold },
  LPSB: { name: "ЛЭСК ао", industry: Industry.EnergySales },
  LSNG: { name: "РСетиЛЭ ао", industry: Industry.Electricity },
  LSNGP: { name: "РСетиЛЭ ап", industry: Industry.Electricity },
  LSRG: { name: "ЛСР Груп", industry: Industry.Development },
  LVHK: { name: "Левенгук", industry: Industry.IndustrialsOther },
  MAGE: { name: "МагадЭн ао", industry: Industry.Energy },
  MAGEP: { name: "МагадЭн ап", industry: Industry.Energy },
  MAGN: { name: "ММК", industry: Industry.BasicMaterialsBlack },
  MBNK: { name: "МТС-банк", industry: Industry.Banks },
  MDMG: { name: "MDMG-гдр", industry: Industry.Consumer },
  MFGS: { name: "Мегион-ао", industry: Industry.OilGas },
  MFGSP: { name: "Мегион-ап", industry: Industry.OilGas },
  MGKL: { name: "МГКЛ", industry: Industry.Financial },
  MGNT: { name: "Магнит ао", industry: Industry.Retail },
  MGTS: { name: "МГТС4-ао", industry: Industry["Telecom Services"] },
  MGTSP: { name: "МГТС4-ап", industry: Industry["Telecom Services"] },
  MISB: { name: "ТнСэнМарЭл ао", industry: Industry.EnergySales },
  MISBP: { name: "ТнСэнМарЭл ап", industry: Industry.EnergySales },
  MOEX: { name: "Мосбиржа", industry: Industry.Financial },
  MRKC: { name: "РоссЦентр", industry: Industry.Electricity },
  MRKK: { name: "Россети СК", industry: Industry.Electricity },
  MRKP: { name: "РСетиЦП", industry: Industry.Electricity },
  MRKS: { name: "РСетСиб", industry: Industry.Electricity },
  MRKU: { name: "РСетиУр", industry: Industry.Electricity },
  MRKV: { name: "РСетиВол", industry: Industry.Electricity },
  MRKY: { name: "РоссЮг", industry: Industry.Electricity },
  MRKZ: { name: "РСетиСЗ", industry: Industry.Electricity },
  MRSB: { name: "МордЭнСб ап", industry: Industry.EnergySales },
  MSNG: { name: "МосЭнерго", industry: Industry.Energy },
  MSRS: { name: "РСетиМР ао", industry: Industry.Electricity },
  MSTT: { name: "Мостотрест", industry: Industry.Development },
  MTLR: { name: "Мечел ао", industry: Industry.BasicMaterialsBlack },
  MTLRP: { name: "Мечел ап", industry: Industry.BasicMaterialsBlack },
  MTSS: { name: "МТС", industry: Industry["Telecom Services"] },
  MVID: { name: "М-видео", industry: Industry.Retail },
  NAUK: { name: "iНПОНаука", industry: Industry.HighTech },
  NFAZ: { name: "НЕФАЗ", industry: Industry.IndustrialsMachinery },
  NKHP: { name: "НКХП ао", industry: Industry.IndustrialsFarm },
  NKNC: {
    name: "НКНХ ао",
    industry: Industry.BasicMaterialsSpecialtyChemicals,
  },
  NKNCP: {
    name: "НКНХ ап",
    industry: Industry.BasicMaterialsSpecialtyChemicals,
  },
  NKSH: {
    name: "Нижкамшина",
    industry: Industry.BasicMaterialsSpecialtyChemicals,
  },
  NLMK: { name: "НЛМК ао", industry: Industry.BasicMaterialsBlack },
  NMTP: { name: "НМТП ао", industry: Industry.Transport },
  NNSB: { name: "ТНСэнНН ао", industry: Industry.EnergySales },
  NNSBP: { name: "ТНСэнНН ап", industry: Industry.EnergySales },
  NSVZ: { name: "iНаукаСвяз", industry: Industry["Telecom Services"] },
  NVTK: { name: "Новатэк ао", industry: Industry.OilGas },
  OGKB: { name: "ОГК-2 ао", industry: Industry.Energy },
  OKEY: { name: "OKEY-гдр", industry: Industry.Retail },
  OMZZP: { name: "ОМЗ ап", industry: Industry.IndustrialsMachinery },
  OZON: { name: "OZON-адр", industry: Industry.Retail },
  PAZA: { name: "ПавлАвт ао", industry: Industry.IndustrialsMachinery },
  PHOR: { name: "ФосАгро ао", industry: Industry.BasicMaterialsChemicals },
  PIKK: { name: "ПИК ао", industry: Industry.Development },
  PLZL: { name: "Полюс", industry: Industry.BasicMaterialsGold },
  PMSB: { name: "ПермьЭнСб ао", industry: Industry.EnergySales },
  PMSBP: { name: "ПермьЭнСб ап", industry: Industry.EnergySales },
  POLY: { name: "Polymetal", industry: Industry.BasicMaterialsGold },
  POSI: { name: "iПозитив", industry: Industry.HighTech },
  PRFN: { name: "ЧЗСПН", industry: Industry.IndustrialsOther },
  PRMB: { name: "Приморье", industry: Industry.Banks },
  QIWI: { name: "iQiwi", industry: Industry.Financial },
  RASP: { name: "Распадская", industry: Industry.BasicMaterialsMining },
  RBCM: { name: "ГК РБК", industry: Industry.Media },
  RDRB: { name: "РДБанк ао", industry: Industry.Banks },
  RENI: { name: "Ренессанс", industry: Industry.Financial },
  RGSS: { name: "РГС СК ао", industry: Industry.Financial },
  RKKE: { name: "ЭнергияРКК", industry: Industry.HighTech },
  RNFT: { name: "РуссНфт ао", industry: Industry.OilGas },
  ROLO: { name: "Русолово ао", industry: Industry.BasicMaterialsColor },
  ROSB: { name: "Росбанк ао", industry: Industry.Banks },
  ROSN: { name: "Роснефть", industry: Industry.OilGas },
  ROST: { name: "РОСИНТЕР РЕСТОРАНТС", industry: Industry.Consumer },
  RTGZ: { name: "ГазРнД ао", industry: Industry.Third },
  RTKM: { name: "Ростел ао", industry: Industry["Telecom Services"] },
  RTKMP: { name: "Ростел ап", industry: Industry["Telecom Services"] },
  RTSB: { name: "ТнСэнРст ао", industry: Industry.EnergySales },
  RTSBP: { name: "ТнСэнРст ао", industry: Industry.EnergySales },
  RUAL: { name: "РУСАЛ ао", industry: Industry.BasicMaterialsColor },
  RUSI: { name: "ИКРУСС-ИНВ", industry: Industry.OilGas },
  RZSB: { name: "РязЭнСб ао", industry: Industry.EnergySales },
  SAGO: { name: "СамарЭн ао", industry: Industry.EnergySales },
  SAGOP: { name: "СамарЭн ап", industry: Industry.EnergySales },
  SARE: { name: "СаратЭн ао", industry: Industry.EnergySales },
  SAREP: { name: "СаратЭн ап", industry: Industry.EnergySales },
  SBER: { name: "Сбер ао", industry: Industry.Banks },
  SBERP: { name: "Сбер ап", industry: Industry.Banks },
  SELG: { name: "Селигдар", industry: Industry.BasicMaterialsGold },
  SFIN: { name: "ЭсЭфАй ао", industry: Industry.Financial },
  SGZH: { name: "Сегежа", industry: Industry.IndustrialsOther },
  SIBN: { name: "Газпрнефть", industry: Industry.OilGas },
  SLEN: { name: "Сахэнер ао", industry: Industry.Energy },
  SMLT: { name: "Самолет", industry: Industry.Development },
  SNGS: { name: "Сургнфгз", industry: Industry.OilGas },
  SNGSP: { name: "Сургнфгз-п ", industry: Industry.OilGas },
  SOFL: { name: "iСофтлайн", industry: Industry.Internet },
  SPBE: { name: "СПБ Биржа", industry: Industry.Financial },
  STSB: { name: "СтаврЭнСб ао", industry: Industry.EnergySales },
  STSBP: { name: "СтаврЭнСб ап", industry: Industry.EnergySales },
  SVAV: { name: "Соллерс", industry: Industry.IndustrialsMachinery },
  SVCB: { name: "Совкомбанк", industry: Industry.Banks },
  SVET: { name: "Светофор", industry: Industry.HighTech },
  T: { name: "Т-Техно ао", industry: Industry.Banks },
  TASB: { name: "ТамбЭнСб ао", industry: Industry.EnergySales },
  TASBP: { name: "ТамбЭнСб ап", industry: Industry.EnergySales },
  TATN: { name: "Татнфт Зао", industry: Industry.OilGas },
  TATNP: { name: "Татнфт Зап", industry: Industry.OilGas },
  TCSG: { name: "ТКСХолд ао", industry: Industry.Banks },
  TGKA: { name: "ТГК-1", industry: Industry.Energy },
  TGKB: { name: "ТГК-2 ао", industry: Industry.Energy },
  TGKBP: { name: "ТГК-2 ао", industry: Industry.Energy },
  TGKN: { name: "ТГК-14", industry: Industry.Energy },
  TNSE: { name: "ТНСэнерг", industry: Industry.EnergySales },
  TORS: { name: "ТРК ао", industry: Industry.Electricity },
  TORSP: { name: "ТРК ап", industry: Industry.Electricity },
  TRMK: { name: "ТМК ао", industry: Industry.BasicMaterialsBlack },
  TRNFP: { name: "Транснф ап", industry: Industry.Transport },
  TTLK: { name: "Таттел ао", industry: Industry["Telecom Services"] },
  TUZA: { name: "ТЗА ао", industry: Industry.IndustrialsMachinery },
  UGLD: { name: "ЮГК", industry: Industry.BasicMaterialsGold },
  UKUZ: { name: "Южкузб. ао", industry: Industry.BasicMaterialsMining },
  UNAC: { name: "iАвиастКао", industry: Industry.IndustrialsMachinery },
  UNKL: { name: "ЮУНК ао", industry: Industry.BasicMaterialsColor },
  UPRO: { name: "Юнипро ао", industry: Industry.Energy },
  URKZ: { name: "УрКузница", industry: Industry.BasicMaterialsBlack },
  USBN: { name: "Уралсиб ао", industry: Industry.Banks },
  "VEON-RX": { name: "VEON", industry: Industry["Telecom Services"] },
  UTAR: { name: "ЮТэйр", industry: Industry.Transport },
  UWGN: { name: "ОВК ао", industry: Industry.IndustrialsMachinery },
  VGSB: { name: "ВолгЭнСб ао", industry: Industry.EnergySales },
  VGSBP: { name: "ВолгЭнСб ап", industry: Industry.EnergySales },
  VJGZ: { name: "Варьеган", industry: Industry.OilGas },
  VJGZP: { name: "Варьеган-п", industry: Industry.OilGas },
  VKCO: { name: `МКПАО "ВК"`, industry: Industry.Internet },
  VLHZ: { name: "ВХЗ ао", industry: Industry.BasicMaterialsSpecialtyChemicals },
  VRSB: { name: "ТнСэнВорон ао", industry: Industry.EnergySales },
  VRSBP: { name: "ТнСэнВорон ап", industry: Industry.EnergySales },
  VSMO: { name: "ВСМПО-АВСМ", industry: Industry.BasicMaterialsColor },
  VSYD: { name: "ВыбСуд3 ао", industry: Industry.IndustrialsMachinery },
  VSYDP: { name: "ВыбСуд3 ап", industry: Industry.IndustrialsMachinery },
  VTBR: { name: "ВТБ ао", industry: Industry.Banks },
  WTCM: { name: "ЦМТ ао", industry: Industry.Third },
  WTCMP: { name: "ЦМТ ап", industry: Industry.Third },
  WUSH: { name: "iВушХолдинг", industry: Industry.Transport },
  X5: { name: "КЦ ИКС 5", industry: Industry.Retail },
  YAKG: { name: "Ятэк ао", industry: Industry.OilGas },
  YKEN: { name: "Якутскэнерг ао", industry: Industry.Energy },
  YKENP: { name: "Якутскэнерг ап", industry: Industry.Energy },
  YNDX: { name: "Yandex clA", industry: Industry.Internet },
  YRSB: { name: "ТНСэнЯр ао", industry: Industry.EnergySales },
  YRSBP: { name: "ТНСэнЯр ап", industry: Industry.EnergySales },
  ZAYM: { name: "Займер ао", industry: Industry.Banks },
  ZILL: { name: "ЗИЛ ао", industry: Industry.Transport },
  ZVEZ: { name: "Звезда ао", industry: Industry.IndustrialsMachinery },
};
